### PR TITLE
catch NaN properly and also end response after 404

### LINKED ISSUE #745: sentry error: invalid input syntax for integer: "'NaN'"
we added Number.isNaN checks to article routes, but Number.isNaN("string") returns false.

Screenshot 2019-09-05 12 46 55

we should instead check that the id is an integer.

Screenshot 2019-09-05 12 42 57

### PR DESCRIPTION
**Pull request by dethe**
Fixes #745 

1. Much more robust checks for NaN (and in the right place this time!)
2. Log to console on from `logMessage` when on localhost
3. End response at 404 without trying to write further data to it.

### CODE REVIEW

File: api/helpers/things.js [hunk 1]
```diff
@@ -95,14 +95,15 @@ const returnByType = (res, params, article, static, user) => {
 };
 
 const parseGetParams = function(req, type) {
-  return Object.assign({}, req.query, {
+  let parms = Object.assign({}, req.query, {
```
Comment (ascott) [inline api/helpers/things.js]: /s/parms/params

**Comment by ascott** [comment]
1 typo, otherwise LGTM! :shipit:

File: api/helpers/things.js (hunk 1 above)
Comment (dethe) [reply api/helpers/things.js]: Ah, that was supposed to be temporary, good eye.
